// Generated by CoffeeScript 1.6.3
module.exports = function(req, callback) {
  var async, candidates, htmlparser, http, obj, parser, path, url;
  htmlparser = require("htmlparser2");
  parser = new htmlparser.Parser({
    onopentag: function(name, attr) {
      if (name === "link" && attr.type === "application/rss+xml" || attr.type === "application/atom+xml") {
        return candidates.push(attr);
      }
    }
  });
  async = require('async');
  url = require('url');
  path = require('path');
  http = require('http');
  candidates = [];
  obj = url.parse(req);
  return http.get(obj.href, function(res) {
    var body;
    body = "";
    res.on('data', function(chunk) {
      return body += chunk;
    });
    return res.on('end', function() {
      parser.write(body);
      parser.end();
      return async.forEach(candidates, function(cand, cb) {
        if (cand.href.match(/[http|https]:\/\//)) {
          cand.url = cand.href;
        } else {
          cand.url = "" + obj.protocol + "//" + obj.host + cand.href;
        }
        return cb();
      }, function() {
        return callback(null, candidates);
      });
    });
  }).on('error', function(e) {
    return callback(e, null);
  });
};
