// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(req, callback) {
    var async, candidates, htmlparser, http, obj, parser, path, url;

    htmlparser = require("htmlparser2");
    parser = new htmlparser.Parser({
      onopentag: function(name, attr) {
        if (name === "link" && attr.type === "application/rss+xml") {
          return candidates.push(attr);
        }
      }
    });
    async = require('async');
    url = require('url');
    path = require('path');
    http = require('http');
    candidates = [];
    obj = url.parse(req);
    return http.get({
      host: obj.host,
      port: obj.port
    }, function(res) {
      var body;

      body = "";
      res.on('data', function(chunk) {
        return body += chunk;
      });
      return res.on('end', function() {
        parser.write(body);
        parser.end();
        return async.forEach(candidates, function(cand, cb) {
          if (cand.href.match(/[http|https]:\/\//)) {
            cand.url = cand.href;
          } else {
            cand.url = "" + obj.protocol + "//" + obj.host + cand.href;
          }
          return cb();
        }, function() {
          return callback(candidates);
        });
      });
    });
  };

}).call(this);
