// Generated by CoffeeScript 1.6.3
module.exports = function(req, callback) {
  var async, candidates, csDetector, favicon, htmlparser, iconv, parser, request, sitename, sitenameFlag, url;
  htmlparser = require("htmlparser2");
  csDetector = require("node-icu-charset-detector");
  iconv = require('iconv');
  async = require('async');
  url = require('url');
  request = require('request');
  candidates = [];
  sitename = '';
  sitenameFlag = false;
  favicon = '';
  parser = new htmlparser.Parser({
    onopentag: function(name, attr) {
      if (name === "link" && attr.type === "application/rss+xml" || attr.type === "application/atom+xml") {
        candidates.push(attr);
      }
      if (name === 'link' && (attr.rel === 'icon' || attr.rel === 'shortcut icon' || attr.type === 'image/x-icon')) {
        favicon = attr.href;
      }
      if (name === "title") {
        return sitenameFlag = true;
      }
    },
    ontext: function(text) {
      if (sitenameFlag) {
        return sitename = text;
      }
    },
    onclosetag: function(name) {
      if (name === "title") {
        return sitenameFlag = false;
      }
    }
  });
  return request.get({
    uri: req,
    encoding: null
  }, function(err, res, body) {
    var charset, converter, obj;
    if (err != null) {
      callback(err, null);
      return;
    }
    obj = url.parse(req);
    charset = csDetector.detectCharset(body).toString();
    if (charset !== ('utf-8' || 'UTF-8')) {
      converter = new iconv.Iconv(charset, 'utf-8');
      body = converter.convert(body).toString();
    }
    parser.write(body);
    parser.end();
    return async.forEach(candidates, function(cand, cb) {
      var guess;
      cand.sitename = sitename;
      if (cand.href.match(/[http|https]:\/\//)) {
        cand.url = cand.href;
      } else {
        cand.url = "" + obj.protocol + "//" + obj.host + cand.href;
      }
      if (favicon.length > 0) {
        if (favicon.match(/[http|https]:\/\//)) {
          cand.favicon = favicon;
        } else {
          console.log(favicon);
          if (favicon.charAt(0) === '/') {
            cand.favicon = "" + obj.protocol + "//" + obj.host + favicon;
          } else {
            cand.favicon = "" + obj.protocol + "//" + obj.host + "/" + favicon;
          }
        }
        return cb();
      } else {
        guess = "" + obj.protocol + "//" + obj.host + "/favicon.ico";
        return request(guess, function(err, res, body) {
          if (res.statusCode === 200) {
            cand.favicon = guess;
          }
          return cb();
        });
      }
    }, function() {
      if (candidates.length === 0) {
        return callback('no such rss feeds.', null);
      } else {
        return callback(null, candidates);
      }
    });
  });
};
